---
title: "Academic Milestone"
editor: visual
---

-   **August 2008**

    Completed high school from Cherubim and Seraphim College, Ilorin, Nigeria.

-   **October 2009**

    Admitted into the University of Ilorin to study BSc Mathematics

-   **July 2011**

    Awarded MTN Science and Technology Scholarship to cover my undergraduate tuition and expenses

-   **July 2013**

    Graduated from University of Ilorin with first class honor

-   **September 2014**

    Admitted to study MSc Mathematics in Numerical Analysis at the University of Ilorin, Nigeria.

-   **May 2015**

    Awarded Next Einstein Initiative scholarship for a structured taught postgraduate program.

-   **August 2015**

    -   Defended my MSc dissertation at the University of Ilorin, Department of Mathematics on "Collocation approach for the numerical solution of integral equation within a bounded basis function".

    -   Printed the thesis hardcopy and submit

    -   First time embarking in International travel

    -   Started second master program at AIMS South Africa

-   **December 2015**

    Awarded Msc in Mathematics with Distinction from the University of Ilorin

-   **February 2016**

    Completed the AIMS taught courses and transition to the research phase

-   **April 2016**

    Volunteered to teach the high school student from the community of Gugulethu, Western Cape, the basic of mathematical problem solving.

-   **May 2016**

    Defended my AIMS dissertation on " the zeroes of Hermite polynomials and its application to finance".

-   **June 2016**

    Graduated from AIMS South Africa and certificate jointed awarded by University of Cape Town and African Institute of Mathematical Sciences (AIMS).

-   **July 2016**

    -   Volunteered to support African Institute of Mathematical Sciences School Enrichment Centre (AIMSSEC) to further train South Africa high school teaching the use of modern technology in teaching.

    -   Return back o Nigeria after the training.

-   **August 2016**

    Got PhD offer from the University of Kwazulu-Natal, South Africa to work on " Numerical approximation for the solution of integro-differential equation".

-   **September 2016**

    -   Got another PhD offer from University of Western Cape, South Africa.

    -   Got a MSc offer from Pan African University, Kenya for taught course and research in mathematical finance.

    -   I declined the two PhD offer and decided to accept Msc for my third master degree program.

-   **November 2016**

    Travel to Kenya to start my program

-   **December 2017**

    Completed the taught course phase for the program and started with the research phase.

-   **July 2018**

    Submitted my thesis on " Numerical Approach for the pricing of Barrier Options".

-   **August 2018**

    Got a UK research Innovation through the EPSRC - SAMBa scholarship for a integrated doctoral program

-   **October 2018**

    -   Travel to the UK to start my PhD program

    -   Return to Kenya for my Master thesis defense

    -   Pass thesis defense with minor correction

    -   Reflect the examiners correction and re-submit my dissertation

    -   Return to the UK

-   **December 2018**

    -   Jointly awarded MSc in Financial Mathematics by Jomo Kenyatta University of Agriculture and Technology and Pan Africa University Institute of Basic Sciences, Technology and Innovation.

    -   Certificate delivered to my UK Address.

-   **September 2019**

    -   Completed the first year of my SAMBa program

-   **October 2019**

    Proceed with my PhD research

-   **December 2019**

    Awarded Master of Research in Statistical Applied Mathematics by University of Bath, UK making it a total of four (4) MSc degree earned each from different countries.

-   **February 2020**

    I was selected by the Heidelberg Laureate Forum (HLF) as one of the world outstanding young researcher in Mathematics and Computer Science

-   **September 2020**

    HLF networking event for the selected young researcher postponed because of Covid-19

-   **March 2021**

    Passed my PhD confirmation examination

-   **September 2021**

    HLF host the networking event remotely and I was able to connect to Laureates

-   **February 2022**

    I was re-selected by the Heidelberg Laureate Forum (HLF) as one of the world outstanding young researcher in Mathematics and Computer Science

-   **April 2022**

    Won Kovaleskaya European Award

-   **September 2022**

    -   Attended the HLF networking event in Heidelberg, Germany.

-   **October 2022**

    -   Invited to give a talk at the Black Heroes of Mathematics conference in Edinburgh, Scotland

    -   Invited to give a talk at the University of Lafayette, Louisiana, US

-   **January 2023**

    Travel from Bath, UK - Boston, US to participate at the Joint Mathematics Meeting and involve in panel discussion on incorporating research in teaching.

-   **March 2023**

    Invited to give a talk the high school UK

-   **August 2023**

    Invited to participate at the industrial problem solving workshop in Montreal, Canada. Expenses paid by CRM, Canada.

-   **September 2023**

    Submitted my PhD dissertation on "Mathematical modelling and data-driven approach for understanding the impact of climate change".

-   **October 2023**

    Got a postdoctoral research offer from the University of Georgia, US.

-   **November 2023**

    Passed my PhD Viva

-   **January 2024**

    -   Attended PhD graduation ceremony

    -   Travel to the US to commence my PostDoc

-   **February 2024**

    Officially commence the PostDoc at the University of Georgia.
