---
title: "Resume"
editor: visual
---

## Professional Summary

I am a mathematician who brings both theoretical depth and practical experience to quantitative finance. My career began in the financial industry, where I worked as an analyst in banking and consulting. That early exposure to real-world investment challenges led me to pursue advanced academic training, ultimately earning a PhD in Mathematical Sciences. I specialize in applying mathematics alongside programming tools such as Python to build models for asset pricing, portfolio optimization, and financial risk analysis. I have also developed scalable, data-driven solutions that integrate machine learning and statistical modeling. My experience cut across both academic research and industry application, which gives me a unique ability to translate complex theory into tools that inform strategy, uncover patterns, and support sound investment decisions. After several years in research, I am now open to returning to the industry and applying my knowledge in a practical, high-impact setting where I can help teams solve complex financial problems and drive strategic outcomes.

## Education

-   2023: Ph.D. in Mathematical Sciences, University of Bath, UK
-   2019: Master of Research in Statistical Applied Mathematics, University of Bath, UK
-   2018: Master of Science in Financial Mathematics, jointly awarded by Pan African University and Jomo-Kenyatta University of Agriculture and Technology, Nairobi, Kenya
-   2016: Master of Science in Mathematical Sciences, jointly awarded by University of Cape Town and African Institute for Mathematical Sciences, South Africa.
-   2015: Master of Science in Mathematics (with Distinction), University of Ilorin, Nigeria.
-   2013: Bachelor of Science in Mathematics (with First Class Honor), University of Ilorin, Nigeria

## Scholarship and Grants (total approx USD 300, 000)

-   February 2025: National Science Foundation (NSF) Travel Grant

-   July 2024: SISMID Holloran Scholarship

-   July 2023: Centre de recherches mathematiques (CRM) Grant

-   October 2022: University of Louisiana at Lafeyette (ICMA VIII) Travel Grant

-   August 2022: Ecological Society of America Opportunity Fund

-   May 2022: Dipartimenta di Eccellenza Grant, Italian Ministry of Education

-   September 2022: Heidelberg Laureate Forum Foundation Grant

-   December 2021: European Kovalevskaya Grant

-   February 2021 V-Knowledge Exchange in Mathematical Sciences Research Grant

-   September 2018: EPSRC - CDT SAMBa PhD Scholarship

-   November 2017: Africa -ai- Japan Project Innovation Fund

-   August 2016: African Union Commission Scholarship.

-   August 2015: AIMS-NEI Scholarship

-   July 2011: MTN Foundation Science and Technology Undergraduate Scholarship.

## Award and Recognition

2023: University of Bath, [Doctoral Recognition Award](https://www.bath.ac.uk/corporate-information/doctoral-recognition-award-recipients/)

2022: UK [Recognition Award](https://maths4dl.ac.uk/newsevents/chris-budd-receives-government-award-for-covid-modelling-work) for Modeling & Data Support with Prof Chris Budd, Dr Simone Appella and Dr Tina Zhou

2022: HLF [Outstanding Young Researcher](https://www.heidelberg-laureate-forum.org/) in Mathematics and Computer Science

2021: ICMS and MAC-MIGS Modeling Camp, Edinburgh, UK – First Place Winner

2020: UK Graduate [Modelling](https://www.maths.ox.ac.uk/study-here/postgraduate-study/industrially-focused-mathematical-modelling-epsrc-cdt/infomm-events-4%7D%7BModelling) Camp, Oxford, UK - Runner up Prize\`

2019: Maryam Mirzakhani Prize at the International Mathematical Olympiad (IMO).

## Work Experience

**Academic Work Experience**

-   Teaching Assistant, King's College London, United Kingdom

    -   Course Taught:

        -   Statistics in Finance

        -   Introduction to dynamical systems

-   Teaching Assistant, University of Bath, United Kingdom

    -   Course Taught

        -   Numerical Analysis

        -   Methods and Applications

        -   Probability

        -   Quantitative Method

        -   Modelling and Dynamical System.

-   Teaching Assistance, African Institute for Mathematical Sciences, School Enrichment Centre, South Africa.

    -   Subject Taught:

        -   Quantitative Reasoning

        -   Verbal Aptitude

**Research Experience**

-   Senior Research Associate, [University of Georgia](https://www.ceid.uga.edu/2024/03/15/oluwatosin-babasola/), Athens, GA

    -   Research Area: Machine Learning, Mathematical modeling, molecular epidemiology, cost effectiveness assessment, environmental risk.

        -   Built predictive machine learning models which improves classification performance by 25% through feature engineering and model tuning.

        -   Mentored research teams on improving machine learning model efficiency, achieving a 30% reduction in runtime by refining data pipelines and algorithm selection.

        -   Collaborated with academic and industry stakeholders to integrate AI into research processes, leading to the creation of new decision-support tools.

        -   Developed mathematical model and implemented molecular epidemiology approach to effectively study the transmission pathway of Influenza A virus.

        -   Utilized scientific software to analyze and visualize both quantitative and qualitative datasets

-   Research Scientist, [Institute for Mathematical Innovation](https://imibath.ac.uk/), Bath, United Kingdom

    -   Research Area: Machine learning, predictive modeling, statistical data analysis, numerical analysis

        -   Developed and optimized asset pricing and portfolio risk models using Python and statistical techniques, which helped to improve predictive accuracy and support investment decisions

        -   Designed compelling data visualizations and presented findings to both technical and non-technical audiences, enabling data-driven strategic decisions.

        -   Conducted statistical inference and time-series analysis to model market trends, helping refine pricing models under different demographic and economic scenarios.

        -   Developed a machine learning algorithm that classify the UK household income and the spending behavior.

        -   Applied statistical modeling techniques to extract meaningful patterns to inform decision making

**Industrial Experience**

-   Lead Financial Analyst, Infinite Data Consultants Ltd

    -   Core competence: Team management, Data analysis, financial modeling

        -   Built financial risk models and simulations to evaluate exposure to market and credit risks, enabling the executive team to proactively mitigate financial threats.

        -   Leveraged Python to process large financial datasets that help uncover investment opportunities and enhance reporting efficiency.

        -   Led interdisciplinary teams across finance and tech departments to implement data-driven strategies, resulting in more cohesive project execution.

        -   Analyzed complex data to derive actionable insights and inform business decision

        -   Identified trends through data analysis to support strategic planning and operational improvement

-   Analyst, Access Bank, plc

    -   Core competence: Statistical analysis, customer relationship, trading, communication

        -    Applied a modified Black-Scholes model and put-call parity to assess the pricing consistency of options and identify arbitrage opportunities through mispricing.

        -   Valued fixed income and structured products using bond math and scenario analysis which assists the bank portfolio manager in aligning risk-return profiles.

        -   Conducted market and industry research to generate investment insights, that supported asset allocation recommendations for high-net-worth clients.

        -   Generated detailed reports to support decision making processes and developed engaging data visualization to effectively communicate consumer products

## Research Area

-   Mathematical Modeling

-   Trading and Option Pricing

-   Machine Learning

-   Molecular Epidemiology

-   Climate Risk Modeling

## Skills

-   Technical:

    -   Programming Skills : Python, R, SQL and MATLAB

    -   Data Visualization: Python (seaborn, Matplotlib, pandas), R (ggplot2, plotly, shiny)

    -   Time Series Forecasting: Python (statsmodels, arch, Prophet), R (quantmod, forecast, fpp3)

    -   Machine Learning: Scikit-learn, PyTorch, TensorFlow, Keras

    -   Statistical Analysis: Python (statsmodels, scipy), R (stats, car, MASS, glmnet, lme4).

    -   Tools & Environments: Git, Bash, Linux Terminal, Jupyter, VS Code

## Core Competence

-   Deep understanding of financial markets and theoretical trading strategies.

-   Skilled with data analysis with large noisy datasets.

-   Effective in fast-paced, collaborative environments.

-   Strong written and verbal communication skills.

-   Advanced programming in Python, R, and MATLAB.

## Conference and Workshop

-   06 - 08 March 2025: [LatMath Conference](https://www.ipam.ucla.edu/programs/special-events-and-conferences/latmath-2025/), University of California, Los Angeles, USA

-   03 - 05 Jan 2025: [Dynamics Days](https://www.ddays.org/2025/) 2025, Denver, USA.

-   21 - 22 Nov 2024: NSF Workshop on [Data-driven Modeling and Prediction of Rare and Extreme Events](https://datascience.uchicago.edu/events/nsf-workshop-on-data-driven-modeling-and-prediction-of-rare-and-extreme-events/), University of Chicago, USA.

-   01 - 03 Oct 2024: [Institute for Disease Modeling](https://www.idmod.org/symposium/current-symposium/) Annual Symposium, Seattle, WA, USA.

-   04 - 09 Aug 2024: E[cological Society of America](https://www.esa.org/longbeach2024/supporting-ecologists-throughout-their-careers/) Annual Meeting, Long Beach, CA, USA.

-   21 - 24 July 2024: Centers of Excellence for Influenza Research and Response (CEIRR), [3rd Annual Meeting](https://web.cvent.com/event/4214470a-d11a-4758-9c4c-458f39ec5736/websitePage:0ac91a96-4480-4228-9106-384edd078b76%7D), New York Academy of Medicine, New York, USA.

<!-- -->

-   15 - 19 July 2024: [Summer Institute in Statistics and Modeling in Infectious Diseases](https://sph.emory.edu/SISMID/about/index.html%7D%7B16th%20Annual%20SISMID), Emory University, Atlanta, GA, USA.

-   24 - 27 June 2024: [Ecology and Evolution of Infectious Diseases (EEID)](https://web.cvent.com/event/b9c7e658-1431-4030-bc0d-e4aa93816616/summary) , Stanford University, California, USA.

<!-- -->

-   28 - 31 May 2024: [Boston University/Keio University/Tsinghua University](https://math.bu.edu/BKT2024/%7D%7BWorkshop) workshop, Boston University, Boston, USA.

<!-- -->

-   13 - 17 May 2024: [13th Montreal Industrial Problem Solving](https://www.crmath.ca/en/activities/#/type/activity/id/3955%7D%7BWorkshop), University of Montreal, Canada.

<!-- -->

-   04 - 06 Oct 2023: [Panaroma of Mathematics II Conference](https://www.hcm.uni-bonn.de/events/eventpages/2023/panorama2/), Hausdorff Center for Mathematics (HCM), Bonn, Germany.

-   04 - 07 Jan 2023: Joint Mathematics Meetings [(JMM)](https://www.jointmathematicsmeetings.org/meetings/national/jmm2023/2270_intro%7D%7B(JMM)%7D). Boston, USA.

-   28 - 30 Oct 2022: ICMA-VIII, International Conference on Modeling and Analysis of Populations in Biological Systems. University of Louisiana, Lafayette, USA.

-   04 - 05 Oct 2022: Annual [Black](https://ima.org.uk/20113/black-heroes-of-mathematics-conference-2022/%7D%7BBlack) Heroes of Mathematics Conference}. Edinburgh, Scotland, UK.

-   18 - 24 Sept 2022: 9th Heidelberg Laureate Forum, Heidelberg Germany.

-   11 - 13 April 2022: British Applied Mathematics, University of Loughborough, UK.

-   20 - 23 Sept 2021: 8th Heidelberg Laureate Forum, Heidelberg, Germany.

-   13 - 15 July 2021: (Virtual) Study Group on Covid-19 safety in Large, Bath, UK

-   23 - 27 May 2021: (Virtual) Society of Industrial and Applied Mathematics (SIAM) Conference on Applications of Dynamical Systems, US

-   17 - 20 May 2021: [ICMS](https://www.icms.org.uk/events/workshops/ModCamp2021%7D%7BICMS) and MAC-MIGS Modelling Cam, United kingdom.

-   12– 16 April 2021: 165 European Study Group with Industry. University of Durham, UK.

-   25 - 29 Jan 2021: 13 SAMBa Integrative Think Tank, Bath, UK.

-   15 - 17 July 202: UK Graduate [Modelling](https://www.maths.ox.ac.uk/study-here/postgraduate-study/industrially-focused-mathematical-modelling-epsrc-cdt/infomm-events-4%7D%7BModelling) Camp, University of Oxford. UK.

-   21 - 23 Jan 2020: [Geospatial](https://www.bath.ac.uk/events/geospatial-study-group-with-industry/%7D%7BGeospatial) Study Group with Industry with challenge problems from [Natural](https://www.gov.uk/government/organisations/natural-england%7D%7BNatural) England and [Highways](https://highwaysengland.co.uk/%7D%7BHighways) England.

## Leadership and Mentorship

-   2023: Doctoral Ambassador}, University of Bath, UK.

-   2022: Faculty Doctoral Representative}, University of Bath, UK.

-   2022: Project Supervisor, Africa - Oxford Mathematics Mentorship, University of Oxford, UK.

-   2022: Facilitator: Royal Institution, Bath Masterclass, UK.

-   Mentor, Discover Bath Summer School, University of Bath, UK.

-   Exhibitor, Maths of Climate Change, British Science Festival, Chelmsford, UK.

## Professional Membership

-   European Mathematical Society (EMS)

-   Canadian Mathematical Society (CMS)

-   American Mathematical Society (AMS)

-   Ecological Society of America (ESA)

-   Ecological Forecasting Initiatives (EFI)

-   Institute of Electrical and Electronics Engineers (IEEE)

-   International Association of Engineers (IAENG)

-   Institute of Mathematics and its Applications (IMA)

-   Society for Industrial and Applied Mathematics (SIAM)

-   Center for the Ecology of Infectious Diseases (CEID)
